### ISSUE TITLE
Bug: the mouse unable to trigger Autohided taskbar

### ISSUE THREAD

**Issue by seaspeak** [hbl917070/Tiefsee4#50]
When Tiefsee window is maximized, if the taskbar is autohided, the mouse unable to trigger the  taskbar by touching bottom edge of the screen.

**Comment by hbl917070** [comment]
This bug did exist before, but I think I fixed it.
What is your Tiefsee version and OS version?

**Comment by seaspeak** [comment]
> What is your Tiefsee version and OS version?

TieSee 4.2.3 Microsoft Store version
Edition	Windows 10
Version	22H2
OS build	19045.4780

**Comment by seaspeak** [comment]
The nightly also had the autohiding taskbar issue.

**Comment by hbl917070** [comment]
This is a very tricky issue, and it is caused by this piece of code.
```C#
protected override void WndProc(ref Message m) {
    // https://rjcodeadvance.com/final-modern-ui-aero-snap-window-resizing-sliding-menu-c-winforms/
    const int WM_NCCALCSIZE = 0x0083; // Standar Title Bar - Snap Window
    if (m.Msg == WM_NCCALCSIZE && m.WParam.ToInt32() == 1) { // Remove border and keep snap window
        return;
    }
}
```

I have two monitors. The problem exists on the main monitor, while the second monitor is fine. 
So, I think this is a bug in Windows itself. 
The taskbar is a system-level UI, and it should be on top. It’s strange that it gets covered by windows.

**Comment by seaspeak** [comment]
It seems like a lot of projects have encountered this issue, for example this fix: https://github.com/electron/electron/pull/25217
